### ISSUE TITLE
Collapsible drop-down

### ISSUE THREAD

**Issue by alekmlynek** [marshmallow-packages/nova-styling#59]
Not an issue but wishlist. Would be awesome if "resources" became collapsible, then this theme would be perfect.

**Comment by stefvanesch** [comment]
Hey @alekmlynek , great idea. We have a "[Nova Resource Categoriser](https://github.com/marshmallow-packages/categorise-resources)" package for this. We have added this as a dependency so that it works out of the box. We have tagged a 2.0 version so you can use it directly. The package we use here is not fully documented yet, we will try to do that this weekend but if you have any questions we would love to hear from you. Check out the [package](https://github.com/marshmallow-packages/categorise-resources) in action in the screen shot.

<img width="1418" alt="Screenshot 2021-07-30 at 20 31 04" src="https://user-images.githubusercontent.com/46725619/127697066-79f57cce-119e-477d-b5e6-2c1634e58c17.png">

**Comment by alekmlynek** [comment]
This looks amazing. Thank you for all your hard work.
